version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}
    image: ${DOCKER_NAME}
    container_name: bso-blog-production
    ports:
      - "9009:3000"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /prod_app/node_modules
    networks:
      - production-network

networks:
  production-network:
    driver: bridge
