version: "3.8"

services:
  web:
    build: .
    container_name: bso-blog
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      PG_ADMIN_USERNAME: ${PG_ADMIN_USERNAME}
      PG_ADMIN_PASSWORD: ${PG_ADMIN_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
