version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: bso-blog-production
    ports:
      - "9009:9009"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /prod_app/node_modules
    networks:
      - production-network

networks:
  production-network:
    driver: bridge
