version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}
    image: bso-blog:develop
    container_name: bso-blog-develop
    ports:
      - "3000:3000"
    env_file:
      - .env.develop
    volumes:
      - ./app:/app
      - /develop_app/node_modules
    networks:
      - develop-network

networks:
  develop-network:
    driver: bridge
